### ISSUE TITLE
Minter::Db#read locks the object without freeing it

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/active_fedora-noid#65]
https://github.com/projecthydra/active_fedora-noid/blob/master/lib/active_fedora/noid/minter/db.rb#L9

The call to `instance` locks the object, yet we never update or free it.

**Comment by atz** [comment]
Related to larger issues on same topic: #66

**Comment by atz** [comment]
Suggestions from jcoyne in slack:
- Extract a `deserialize(obj)` method from `read`
- make the load `read` does not lock
- update `write!` to load a locked instance and call `deserialize()` on it. 

I agree with the first part at least.  The deserialization should be separate from whether the object is locked or not.  

The end goal here should be to avoid 2 separate queries for the same object.  That means retaining the object.

**Comment by atz** [comment]
I'd argue that `deserialize` is a concern of the MinterState model, since it relies only on MinterState (not Db).

**Comment by atz** [comment]
Resolved by #69
